# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-postgres
# Command to start on workspace startup (optional)
tasks:
  - init: psql < sql/bootstap_db.sql
  - init: psql --username=api  shop < sql/create_tables.sql
  - init: psql --username=api  shop < sql/seed.sql

# command: yarn build
# Ports to expose on workspace startup (optional)
#ports:
#  - port: 8000
#    onOpen: open-preview